[package]
name = "zenoh_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
quick-xml = "0.31.0"
async-std = "1.0"